import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@kizo/ui";
import { Card, CardContent } from "../../../../packages/ui/src/components/Card";
import { Home, ArrowLeft } from "lucide-react";
import { useAppNavigation } from "../utils/useAppNavigation";
export function NotFoundPage() {
    const { goHome, goToDashboard, goToPayment, goToTransactions } = useAppNavigation();
    return (_jsx("div", { className: "min-h-screen bg-black flex items-center justify-center px-4", children: _jsxs("div", { className: "max-w-2xl mx-auto text-center", children: [_jsxs("div", { className: "mb-8", children: [_jsx("div", { className: "text-8xl lg:text-9xl font-thin text-transparent bg-gradient-to-r from-cyan-400 to-blue-400 bg-clip-text mb-4", children: "404" }), _jsx("div", { className: "w-32 h-1 bg-gradient-to-r from-cyan-400 to-blue-400 mx-auto rounded-full opacity-50" })] }), _jsxs("div", { className: "mb-12", children: [_jsx("h1", { className: "text-3xl lg:text-4xl font-thin text-white mb-4", children: "Page Not Found" }), _jsx("p", { className: "text-xl text-slate-400 leading-relaxed", children: "Oops! The page you're looking for seems to have vanished into the digital void. Don't worry, it happens to the best of us." })] }), _jsx(Card, { className: "bg-slate-900/30 border-slate-800 mb-8", children: _jsxs(CardContent, { className: "p-8", children: [_jsx("h2", { className: "text-xl font-semibold text-white mb-6", children: "What would you like to do?" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsxs(Button, { variant: "glow", className: "h-16 flex-col space-y-2", onClick: goHome, children: [_jsx(Home, { className: "w-6 h-6" }), _jsx("span", { children: "Go Home" })] }), _jsxs(Button, { variant: "outline", className: "h-16 flex-col space-y-2 border-slate-700 hover:border-cyan-500/50 bg-transparent", onClick: () => window.history.back(), children: [_jsx(ArrowLeft, { className: "w-6 h-6" }), _jsx("span", { children: "Go Back" })] })] })] }) }), _jsxs("div", { className: "space-y-4", children: [_jsx("h3", { className: "text-lg font-medium text-white", children: "Popular Pages" }), _jsxs("div", { className: "flex flex-wrap justify-center gap-4", children: [_jsx(Button, { variant: "ghost", size: "sm", onClick: goToDashboard, className: "text-slate-400 hover:text-cyan-400", children: "Dashboard" }), _jsx(Button, { variant: "ghost", size: "sm", onClick: goToPayment, className: "text-slate-400 hover:text-cyan-400", children: "Send Payment" }), _jsx(Button, { variant: "ghost", size: "sm", onClick: goToTransactions, className: "text-slate-400 hover:text-cyan-400", children: "Transactions" })] })] })] }) }));
}
